---
# yamllint disable-line rule:line-length
# Based on https://github.com/Azure-Samples/azure-pipelines-python/blob/master/.azure-pipelines/simple_package.1-multi-target.yml
# another ref. https://github.com/tox-dev/azure-pipelines-template
variables:
  package: python-anyconfig-json5-backend
  srcDirectory: src/$(package)
  testsDirectory: tests/$(package)

jobs:
  - job: Build
    strategy:
      matrix:
        python37:
          pythonVersion: 3.7
        python38:
          pythonVersion: 3.8
        python39:
          pythonVersion: 3.9
        python38-anyconfig:
          pythonVersion: 3.8
          subVer: -anyconfig
        python38-json5:
          pythonVersion: 3.8
          subVer: -json5

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      # yamllint disable-line rule:line-length
      TOXENV: py${{ replace(variables.pythonVersion, '.', '') }}${{ variables.subVer }}

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)

      - script: |
          python -m pip install --upgrade pip
          pip install tox
        displayName: Install some more test time dependencies

      - script: |
          echo $(TOXENV)
          tox -e $(TOXENV)
        displayName: Run tests using tox

# vim:sw=2:ts=2:et:
